/**
 * The catalog's genre and mood vocabulary, as the artist upload form offers it
 * (#2059). Genres stay free text at upload; this list is the de-facto
 * vocabulary that the AI DJ presets are checked against and that
 * `backend/src/modules/recommendations/taste_edit_vocabulary.ts` mirrors.
 */
export const CATALOG_GENRE_OPTIONS: readonly string[] = [
  "Acid House",
  "Acid Jazz",
  "Acoustic",
  "Afro-Pop",
  "Afrobeat",
  "Amapiano",
  "Alternative",
  "Ambient",
  "Americana",
  "Baile Funk",
  "Big Room",
  "Bluegrass",
  "Blues",
  "Bossa Nova",
  "Breakbeat",
  "Classical",
  "Country",
  "Dance",
  "Dancehall",
  "Deep House",
  "Disco",
  "Drill",
  "Drum & Bass",
  "Dub",
  "Dubstep",
  "EDM",
  "Electronic",
  "Electro",
  "Experimental",
  "Folk",
  "Funk",
  "Future Bass",
  "Future House",
  "Garage",
  "Glitch",
  "Gospel",
  "Grime",
  "Hardcore",
  "Hardstyle",
  "Heavy Metal",
  "Hip-Hop",
  "House",
  "Hyperpop",
  "IDM",
  "Indie",
  "Industrial",
  "J-Pop",
  "Jazz",
  "Jungle",
  "K-Pop",
  "Kuduro",
  "Latin",
  "Lo-Fi",
  "Melodic Techno",
  "Metal",
  "Minimal",
  "Musiques du monde",
  "New Age",
  "Nu-Disco",
  "Opera",
  "Phonk",
  "Pop",
  "Post-Punk",
  "Psytrance",
  "Psych-Rock",
  "Punk",
  "R&B",
  "Rap",
  "Reggae",
  "Reggaeton",
  "Rock",
  "Ska",
  "Slap House",
  "Soul",
  "Soulful House",
  "Synthpop",
  "Synthwave",
  "Tech House",
  "Techno",
  "Trance",
  "Trap",
  "Trip-Hop",
  "Tropical House",
  "UK Garage",
  "Vaporwave",
  "World",
];

/** Mood tags an artist can add to a release at upload. */
export const MOOD_TAG_OPTIONS: readonly string[] = ["Focus", "Hype", "Chill", "Dark", "Zen", "Club", "Late Night", "Warm"];
