import type { Release } from "./api";

/**
 * Rendered on the home page when `/catalog/published` returns an empty
 * array (e.g. fresh staging). Prevents the "shimmer-forever" half-built
 * look reviewers would otherwise see. Six items because the Latest
 * Masterings grid looks balanced at 1 featured + 5 standard.
 */
export const FALLBACK_RELEASES: Release[] = [
  {
    id: "fallback-release-1",
    artistId: "fallback-artist-1",
    title: "The Horizon Is Home",
    status: "PUBLISHED",
    type: "SINGLE",
    primaryArtist: "Golden Youth",
    genre: "Indie",
    label: null,
    releaseDate: "2026-01-12T00:00:00.000Z",
    explicit: false,
    createdAt: "2026-01-12T00:00:00.000Z",
    artworkUrl: null,
  },
  {
    id: "fallback-release-2",
    artistId: "fallback-artist-2",
    title: "Breaking Into Day",
    status: "PUBLISHED",
    type: "SINGLE",
    primaryArtist: "Lunar Garden",
    genre: "Dream Pop",
    label: null,
    releaseDate: "2026-02-04T00:00:00.000Z",
    explicit: false,
    createdAt: "2026-02-04T00:00:00.000Z",
    artworkUrl: null,
  },
  {
    id: "fallback-release-3",
    artistId: "fallback-artist-3",
    title: "Cinematic Orchestral Score",
    status: "PUBLISHED",
    type: "EP",
    primaryArtist: "AI (Lyria)",
    genre: "Electronic",
    label: null,
    releaseDate: "2026-02-18T00:00:00.000Z",
    explicit: false,
    createdAt: "2026-02-18T00:00:00.000Z",
    artworkUrl: null,
  },
  {
    id: "fallback-release-4",
    artistId: "fallback-artist-4",
    title: "Low Orbit",
    status: "PUBLISHED",
    type: "SINGLE",
    primaryArtist: "Nightshift",
    genre: "Electronic",
    label: null,
    releaseDate: "2026-03-03T00:00:00.000Z",
    explicit: false,
    createdAt: "2026-03-03T00:00:00.000Z",
    artworkUrl: null,
  },
  {
    id: "fallback-release-5",
    artistId: "fallback-artist-5",
    title: "Soft Machine",
    status: "PUBLISHED",
    type: "SINGLE",
    primaryArtist: "Marlowe Rey",
    genre: "Alt R&B",
    label: null,
    releaseDate: "2026-03-17T00:00:00.000Z",
    explicit: false,
    createdAt: "2026-03-17T00:00:00.000Z",
    artworkUrl: null,
  },
  {
    id: "fallback-release-6",
    artistId: "fallback-artist-6",
    title: "Signal To Noise",
    status: "PUBLISHED",
    type: "ALBUM",
    primaryArtist: "Kite Collective",
    genre: "Post-Rock",
    label: null,
    releaseDate: "2026-04-01T00:00:00.000Z",
    explicit: false,
    createdAt: "2026-04-01T00:00:00.000Z",
    artworkUrl: null,
  },
];
