import { AnalyticsIngestService } from "../modules/analytics/analytics_ingest.service";
import { AnalyticsService } from "../modules/analytics/analytics.service";
import { AnalyticsWarehouseExportService } from "../modules/analytics/analytics_warehouse";

describe("analytics", () => {
  it("aggregates plays and payouts by artist", async () => {
    const ingest = new AnalyticsIngestService();
    const analytics = new AnalyticsService(ingest);

    await ingest.ingest({
      eventName: "license.granted",
      occurredAt: new Date().toISOString(),
      payload: { artistId: "artist-1", trackId: "track-1", title: "Neon Drift" },
    });
    await ingest.ingest({
      eventName: "payment.settled",
      occurredAt: new Date().toISOString(),
      payload: {
        artistId: "artist-1",
        trackId: "track-1",
        title: "Neon Drift",
        amountUsd: 1.5,
        paymentToken: "0x0000000000000000000000000000000000000000",
        paymentAssetId: "local:eth",
        paymentAssetSymbol: "ETH",
        paymentAssetDecimals: 18,
        settlementAmount: "0.0005",
        settlementAmountUnits: "500000000000000",
      },
    });

    const result = await analytics.getArtistStats("artist-1", 7);
    expect(result.summary.totalPlays).toBe(1);
    expect(result.summary.totalPayoutUsd).toBe(1.5);
    expect(result.summary.payoutsByAsset).toEqual([
      expect.objectContaining({
        paymentToken: "0x0000000000000000000000000000000000000000",
        assetId: "local:eth",
        symbol: "ETH",
        settlementAmount: "0.0005",
        settlementAmountUnits: "500000000000000",
        canonicalAmountUsd: 1.5,
        count: 1,
      }),
    ]);
    expect(result.tracks[0].payoutUsd).toBe(1.5);
    expect(result.tracks[0].payoutsByAsset[0].symbol).toBe("ETH");
  });

  it("builds v1 dashboard breakdowns", async () => {
    const ingest = new AnalyticsIngestService();
    const analytics = new AnalyticsService(ingest);

    await ingest.ingest({
      eventName: "license.granted",
      occurredAt: new Date().toISOString(),
      payload: {
        artistId: "artist-2",
        trackId: "track-9",
        title: "Pulse",
        sessionId: "session-9",
        source: "agent",
      },
    });
    await ingest.ingest({
      eventName: "payment.settled",
      occurredAt: new Date().toISOString(),
      payload: {
        artistId: "artist-2",
        trackId: "track-9",
        title: "Pulse",
        sessionId: "session-9",
        source: "agent",
        amountUsd: 2,
        paymentToken: "0x1111111111111111111111111111111111111111",
        paymentAssetId: "base-sepolia:usdc",
        paymentAssetSymbol: "USDC",
        paymentAssetDecimals: 6,
        settlementAmount: "2",
        settlementAmountUnits: "2000000",
      },
    });

    const result = await analytics.getArtistDashboard("artist-2", 30);
    expect(result.summary.totalPlays).toBe(1);
    expect(result.sessions[0].payoutUsd).toBe(2);
    expect(result.sessions[0].payoutsByAsset[0]).toEqual(
      expect.objectContaining({
        symbol: "USDC",
        settlementAmount: "2",
        canonicalAmountUsd: 2,
      }),
    );
    expect(result.export.payoutsByAsset[0].symbol).toBe("USDC");
    expect(result.sources[0].source).toBe("agent");
  });

  it("reads current reports from analytics facts generated by warehouse layers", async () => {
    const ingest = new AnalyticsIngestService();
    const warehouse = new AnalyticsWarehouseExportService(ingest);
    const analytics = new AnalyticsService(ingest, warehouse);

    await ingest.ingest({
      eventName: "playback.completed",
      occurredAt: new Date().toISOString(),
      payload: {
        artistId: "artist-warehouse",
        trackId: "track-warehouse",
        title: "Fact Pattern",
        sessionId: "session-warehouse",
        source: "web",
      },
    });
    await ingest.ingest({
      eventName: "commerce.settled",
      occurredAt: new Date().toISOString(),
      payload: {
        artistId: "artist-warehouse",
        trackId: "track-warehouse",
        title: "Fact Pattern",
        sessionId: "session-warehouse",
        source: "web",
        canonicalAmountUsd: 3.25,
        paymentToken: "0x2222222222222222222222222222222222222222",
        paymentAssetId: "base:usdc",
        paymentAssetSymbol: "USDC",
        paymentAssetDecimals: 6,
        settlementAmount: "3.25",
        settlementAmountUnits: "3250000",
      },
    });

    const result = await analytics.getArtistDashboard("artist-warehouse", 30);

    expect(result.summary.totalPlays).toBe(1);
    expect(result.summary.totalPayoutUsd).toBe(3.25);
    expect(result.tracks[0]).toEqual(
      expect.objectContaining({
        trackId: "track-warehouse",
        title: "Fact Pattern",
        plays: 1,
        payoutUsd: 3.25,
      }),
    );
    expect(result.sessions[0]).toEqual(
      expect.objectContaining({
        sessionId: "session-warehouse",
        plays: 1,
        payoutUsd: 3.25,
      }),
    );
    expect(result.sources[0]).toEqual(expect.objectContaining({ source: "web", plays: 1 }));
  });
});
