import { AnalyticsIngestService } from "../modules/analytics/analytics_ingest.service";
import { AnalyticsService } from "../modules/analytics/analytics.service";
import { ArtistAnalyticsReportSource } from "../modules/analytics/analytics_bigquery_report";
import { AnalyticsWarehouseExportService } from "../modules/analytics/analytics_warehouse";
import { AnalyticsCatalogMetadataService } from "../modules/analytics/analytics_catalog_metadata.service";

describe("analytics", () => {
  it("aggregates plays and payouts by artist", async () => {
    const ingest = new AnalyticsIngestService();
    const analytics = new AnalyticsService(ingest);
    const occurredAt = new Date(Date.now() - 60_000).toISOString();

    await ingest.ingest({
      eventName: "license.granted",
      occurredAt,
      payload: { artistId: "artist-1", trackId: "track-1", title: "Neon Drift" },
    });
    await ingest.ingest({
      eventName: "payment.settled",
      occurredAt,
      payload: {
        artistId: "artist-1",
        trackId: "track-1",
        title: "Neon Drift",
        amountUsd: 1.5,
        paymentToken: "0x0000000000000000000000000000000000000000",
        paymentAssetId: "local:eth",
        paymentAssetSymbol: "ETH",
        paymentAssetDecimals: 18,
        settlementAmount: "0.0005",
        settlementAmountUnits: "500000000000000",
      },
    });

    const result = await analytics.getArtistStats("artist-1", 7);
    expect(result.summary.totalPlays).toBe(1);
    expect(result.summary.totalPayoutUsd).toBe(1.5);
    expect(result.summary.payoutsByAsset).toEqual([
      expect.objectContaining({
        paymentToken: "0x0000000000000000000000000000000000000000",
        assetId: "local:eth",
        symbol: "ETH",
        settlementAmount: "0.0005",
        settlementAmountUnits: "500000000000000",
        canonicalAmountUsd: 1.5,
        count: 1,
      }),
    ]);
    expect(result.tracks[0].payoutUsd).toBe(1.5);
    expect(result.tracks[0].payoutsByAsset[0].symbol).toBe("ETH");
  });

  it("builds v1 dashboard breakdowns", async () => {
    const ingest = new AnalyticsIngestService();
    const analytics = new AnalyticsService(ingest);

    await ingest.ingest({
      eventName: "license.granted",
      occurredAt: "2026-05-20T08:30:00.000Z",
      payload: {
        artistId: "artist-2",
        trackId: "track-9",
        title: "Pulse",
        sessionId: "session-9",
        source: "agent",
      },
    });
    await ingest.ingest({
      eventName: "payment.settled",
      occurredAt: "2026-05-20T08:31:00.000Z",
      payload: {
        artistId: "artist-2",
        trackId: "track-9",
        title: "Pulse",
        sessionId: "session-9",
        source: "agent",
        amountUsd: 2,
        paymentToken: "0x1111111111111111111111111111111111111111",
        paymentAssetId: "base-sepolia:usdc",
        paymentAssetSymbol: "USDC",
        paymentAssetDecimals: 6,
        settlementAmount: "2",
        settlementAmountUnits: "2000000",
      },
    });
    await ingest.ingest({
      eventName: "rights.route_decided",
      occurredAt: "2026-05-20T08:32:00.000Z",
      payload: {
        artistId: "artist-2",
        releaseId: "release-9",
        route: "STANDARD_ESCROW",
        evidenceTypes: ["rights_metadata"],
        decisionReason: "artist profile verified",
      },
    });

    const result = await analytics.getArtistDashboard("artist-2", 30);
    expect(result.summary.totalPlays).toBe(1);
    expect(result.sessions[0].payoutUsd).toBe(2);
    expect(result.sessions[0].payoutsByAsset[0]).toEqual(
      expect.objectContaining({
        symbol: "USDC",
        settlementAmount: "2",
        canonicalAmountUsd: 2,
      }),
    );
    expect(result.export.payoutsByAsset[0].symbol).toBe("USDC");
    expect(result.sources[0].source).toBe("agent");
    expect(result.protection).toEqual(
      expect.objectContaining({
        totalDecisions: 1,
        releasesWithDecisions: 1,
        marketplaceReadyReleases: 1,
        restrictedReleases: 0,
        blockedReleases: 0,
      }),
    );
    expect(result.protection.routes[0]).toEqual(
      expect.objectContaining({
        route: "STANDARD_ESCROW",
        decisions: 1,
        releases: 1,
      }),
    );
  });

  it("reads current reports from analytics facts generated by warehouse layers", async () => {
    const ingest = new AnalyticsIngestService();
    const warehouse = new AnalyticsWarehouseExportService(ingest);
    const analytics = new AnalyticsService(ingest, warehouse);

    await ingest.ingest({
      eventName: "playback.completed",
      occurredAt: "2026-05-20T09:00:00.000Z",
      payload: {
        artistId: "artist-warehouse",
        trackId: "track-warehouse",
        title: "Fact Pattern",
        sessionId: "session-warehouse",
        source: "web",
      },
    });
    await ingest.ingest({
      eventName: "commerce.settled",
      occurredAt: "2026-05-20T09:01:00.000Z",
      payload: {
        artistId: "artist-warehouse",
        trackId: "track-warehouse",
        title: "Fact Pattern",
        sessionId: "session-warehouse",
        source: "web",
        canonicalAmountUsd: 3.25,
        paymentToken: "0x2222222222222222222222222222222222222222",
        paymentAssetId: "base:usdc",
        paymentAssetSymbol: "USDC",
        paymentAssetDecimals: 6,
        settlementAmount: "3.25",
        settlementAmountUnits: "3250000",
      },
    });

    const result = await analytics.getArtistDashboard("artist-warehouse", 30);

    expect(result.summary.totalPlays).toBe(1);
    expect(result.summary.totalPayoutUsd).toBe(3.25);
    expect(result.tracks[0]).toEqual(
      expect.objectContaining({
        trackId: "track-warehouse",
        title: "Fact Pattern",
        plays: 1,
        payoutUsd: 3.25,
      }),
    );
    expect(result.sessions[0]).toEqual(
      expect.objectContaining({
        sessionId: "session-warehouse",
        plays: 1,
        payoutUsd: 3.25,
      }),
    );
    expect(result.sources[0]).toEqual(expect.objectContaining({ source: "web", plays: 1 }));
  });

  it("enriches dashboard track names from catalog metadata when facts omit titles", async () => {
    const ingest = new AnalyticsIngestService();
    const warehouse = new AnalyticsWarehouseExportService(ingest);
    const catalogMetadata: Pick<AnalyticsCatalogMetadataService, "findTracks"> = {
      findTracks: jest.fn().mockResolvedValue(
        new Map([
          [
            "track-metadata",
            {
              trackId: "track-metadata",
              title: "Zongi Sanga",
              releaseId: "release-metadata",
              releaseTitle: "Extra Musica",
              artistId: "artist-metadata",
              artistName: "Grey",
            },
          ],
        ]),
      ),
    };
    const analytics = new AnalyticsService(
      ingest,
      warehouse,
      undefined,
      catalogMetadata as AnalyticsCatalogMetadataService,
    );

    await ingest.ingest({
      eventName: "playback.completed",
      occurredAt: "2026-05-20T09:00:00.000Z",
      payload: {
        artistId: "artist-metadata",
        trackId: "track-metadata",
        sessionId: "session-metadata",
        source: "web_player",
      },
    });

    const result = await analytics.getArtistDashboard("artist-metadata", 30);

    expect(catalogMetadata.findTracks).toHaveBeenCalledWith(["track-metadata"]);
    expect(result.topTracks[0]).toEqual(
      expect.objectContaining({
        trackId: "track-metadata",
        title: "Zongi Sanga",
        plays: 1,
      }),
    );
    expect(result.trackPerformance[0]).toEqual(
      expect.objectContaining({
        trackId: "track-metadata",
        title: "Zongi Sanga",
      }),
    );
  });

  it("returns explicit no-data metadata instead of placeholder dashboard values", async () => {
    const ingest = new AnalyticsIngestService();
    const analytics = new AnalyticsService(ingest);

    const result = await analytics.getArtistDashboard("artist-empty", 30);

    expect(result.summary.totalPlays).toBe(0);
    expect(result.summary.totalPayoutUsd).toBe(0);
    expect(result.tracks).toEqual([]);
    expect(result.playsOverTime).toEqual([]);
    expect(result.meta).toEqual(
      expect.objectContaining({
        source: "warehouse_export",
        isEmpty: true,
        freshness: { asOf: null, lagSeconds: null },
      }),
    );
    expect(result.listenerGrowth.status).toBe("unavailable");
    expect(result.protection).toEqual({
      totalDecisions: 0,
      releasesWithDecisions: 0,
      marketplaceReadyReleases: 0,
      restrictedReleases: 0,
      blockedReleases: 0,
      routes: [],
    });
  });

  it("builds aggregate AI DJ recommendation quality metrics without user drilldowns", async () => {
    const ingest = new AnalyticsIngestService();
    const analytics = new AnalyticsService(ingest);
    const base = Date.now() - 60_000;
    const at = (offsetMs: number) => new Date(base + offsetMs).toISOString();

    await ingest.ingest({
      eventName: "agent.intent_selected",
      occurredAt: at(0),
      subjectType: "agent_config",
      subjectId: "agent-config-1",
      payload: {
        source: "agent_session_intent_panel",
        intent: "focus",
        intentName: "Neural Flow",
        mood: "focused",
        tasteSignalSource: "bigquery",
        materializationVersion: "baseline/v1",
      },
    });
    await ingest.ingest({
      eventName: "agent.session_started",
      occurredAt: at(1_000),
      sessionId: "agent-session-1",
      subjectType: "agent_session",
      subjectId: "agent-session-1",
      payload: {
        source: "agent_session_intent_panel",
        intent: "focus",
        intentName: "Neural Flow",
        strategy: "model-assisted",
        tasteSignalSource: "bigquery",
        materializationVersion: "baseline/v1",
      },
    });
    await ingest.ingest({
      eventName: "agent.next_pick_requested",
      occurredAt: at(2_000),
      sessionId: "agent-session-1",
      subjectType: "agent_session",
      subjectId: "agent-session-1",
      payload: {
        source: "agent_next_pick_card",
        status: "ok",
        trackId: "track-agent-1",
        intent: "focus",
        intentName: "Neural Flow",
        strategy: "model-assisted",
        tasteSignalSource: "bigquery",
        materializationVersion: "baseline/v1",
      },
    });
    await ingest.ingest({
      eventName: "playback.completed",
      occurredAt: at(3_000),
      sessionId: "agent-session-1",
      subjectType: "track",
      subjectId: "track-agent-1",
      payload: {
        source: "agent_queue",
        artistId: "artist-agent",
        trackId: "track-agent-1",
        completionRatio: 0.92,
        firstPick: true,
      },
    });
    await ingest.ingest({
      eventName: "library.saved",
      occurredAt: at(4_000),
      sessionId: "agent-session-1",
      subjectType: "track",
      subjectId: "track-agent-1",
      payload: {
        source: "agent_queue",
        trackId: "track-agent-1",
      },
    });
    await ingest.ingest({
      eventName: "commerce.settled",
      occurredAt: at(5_000),
      sessionId: "agent-session-1",
      subjectType: "track",
      subjectId: "track-agent-1",
      payload: {
        source: "agent_purchase",
        trackId: "track-agent-1",
        canonicalAmountUsd: 2.5,
      },
    });
    await ingest.ingest({
      eventName: "agent.session_stopped",
      occurredAt: at(6_000),
      sessionId: "agent-session-1",
      subjectType: "agent_session",
      subjectId: "agent-session-1",
      payload: {
        source: "agent_command_bar",
        intent: "focus",
        intentName: "Neural Flow",
        sessionDurationMs: 180000,
      },
    });
    await ingest.ingest({
      eventName: "playback.completed",
      occurredAt: at(7_000),
      subjectType: "track",
      subjectId: "track-unrelated",
      payload: {
        source: "web_player",
        artistId: "artist-unrelated",
        trackId: "track-unrelated",
        completionRatio: 1,
      },
    });

    const result = await analytics.getAgentQualityDashboard(7);

    expect(result.summary.sessionsStarted).toBe(1);
    expect(result.summary.nextPickRequests).toBe(1);
    expect(result.summary.acceptedPicks).toBe(1);
    expect(result.summary.acceptanceRate).toBe(1);
    expect(result.summary.playbackCompletions).toBe(1);
    expect(result.summary.saves).toBe(1);
    expect(result.summary.purchases).toBe(1);
    expect(result.summary.purchaseUsd).toBe(2.5);
    expect(result.summary.averageSessionDurationMs).toBe(180000);
    expect(result.intentBreakdown[0]).toEqual(
      expect.objectContaining({
        key: "focus",
        label: "Neural Flow",
        acceptanceRate: 1,
      }),
    );
    expect(result.tasteSourceBreakdown[0]).toEqual(
      expect.objectContaining({
        key: "bigquery",
      }),
    );
    expect(result.versionBreakdown[0]).toEqual(
      expect.objectContaining({
        key: "baseline/v1",
      }),
    );
    expect(result.privacy.excludes).toContain("actor ids");
  });

  it("aggregates dashboard metrics from a BigQuery-backed report source", async () => {
    const ingest = new AnalyticsIngestService();
    const reportSource: ArtistAnalyticsReportSource = {
      async listArtistFacts() {
        return {
          facts: [
            {
              factId: "fact_play",
              factType: "playback_event",
              eventId: "evt_play",
              occurredAt: "2026-05-20T10:00:00.000Z",
              occurredDate: "2026-05-20",
              artistId: "artist-bq",
              trackId: "track-bq",
              count: 1,
              dimensions: {
                eventName: "playback.completed",
                title: "Warehouse Signal",
                sessionId: "session-bq",
                source: "web",
              },
            },
            {
              factId: "fact_play_2",
              factType: "playback_event",
              eventId: "evt_play_2",
              occurredAt: "2026-05-20T10:00:30.000Z",
              occurredDate: "2026-05-20",
              artistId: "artist-bq",
              trackId: "track-bq",
              count: 1,
              dimensions: {
                eventName: "playback.completed",
                title: "Warehouse Signal",
                sessionId: "session-bq-2",
                source: "web",
              },
            },
            {
              factId: "fact_rights",
              factType: "rights_event",
              eventId: "evt_rights",
              occurredAt: "2026-05-20T10:02:00.000Z",
              occurredDate: "2026-05-20",
              artistId: "artist-bq",
              releaseId: "release-bq",
              count: 1,
              dimensions: {
                eventName: "rights.route_decided",
                route: "QUARANTINED_REVIEW",
              },
            },
            {
              factId: "fact_payout",
              factType: "commerce_event",
              eventId: "evt_payout",
              occurredAt: "2026-05-20T10:01:00.000Z",
              occurredDate: "2026-05-20",
              artistId: "artist-bq",
              trackId: "track-bq",
              canonicalAmountUsd: 4.5,
              count: 1,
              dimensions: {
                eventName: "commerce.settled",
                title: "Warehouse Signal",
                sessionId: "session-bq",
                source: "web",
                paymentToken: "0x3333333333333333333333333333333333333333",
                paymentAssetId: "base:usdc",
                paymentAssetSymbol: "USDC",
                paymentAssetDecimals: 6,
                settlementAmountUnits: "4500000",
              },
            },
          ],
          views: [
            {
              viewName: "daily_event_artist_track",
              grain: "day_event_artist_track",
              date: "2026-05-20",
              eventName: "playback.completed",
              artistId: "artist-bq",
              trackId: "track-bq",
              eventCount: 1,
              playCount: 1,
              payoutUsd: 0,
            },
            {
              viewName: "daily_event_artist_track",
              grain: "day_event_artist_track",
              date: "2026-05-20",
              eventName: "commerce.settled",
              artistId: "artist-bq",
              trackId: "track-bq",
              eventCount: 1,
              playCount: 0,
              payoutUsd: 4.5,
            },
          ],
          metadata: {
            source: "bigquery",
            generatedAt: "2026-05-22T12:00:00.000Z",
            timeWindow: {
              from: "2026-04-22T12:00:00.000Z",
              to: "2026-05-22T12:00:00.000Z",
              days: 30,
            },
            freshness: {
              asOf: "2026-05-20T10:01:00.000Z",
              lagSeconds: 179940,
            },
            isEmpty: false,
            cache: {
              hit: false,
              ttlSeconds: 60,
            },
          },
        };
      },
    };
    const analytics = new AnalyticsService(ingest, undefined, reportSource);

    const result = await analytics.getArtistDashboard("artist-bq", 30);

    expect(result.summary.totalPlays).toBe(2);
    expect(result.summary.totalPayoutUsd).toBe(4.5);
    expect(result.topTracks[0]).toEqual(
      expect.objectContaining({
        trackId: "track-bq",
        title: "Warehouse Signal",
        plays: 2,
        payoutUsd: 4.5,
      }),
    );
    expect(result.playsOverTime).toEqual([{ date: "2026-05-20", plays: 2, payoutUsd: 4.5 }]);
    expect(result.trackPerformance[0].payoutsByAsset[0]).toEqual(
      expect.objectContaining({
        symbol: "USDC",
        settlementAmount: "4.5",
        canonicalAmountUsd: 4.5,
      }),
    );
    expect(result.protection.restrictedReleases).toBe(1);
    expect(result.protection.routes[0]).toEqual(
      expect.objectContaining({
        route: "QUARANTINED_REVIEW",
        latestDecisionAt: "2026-05-20T10:02:00.000Z",
      }),
    );
    expect(result.meta.source).toBe("bigquery");
    expect(result.export.freshness.asOf).toBe("2026-05-20T10:01:00.000Z");
  });
});
