/**
 * AI parts placement (#1901 S4 PR 2) — pure unit tests.
 *
 * The parity block replays the committed fixture
 * `remix-parts-v1.parity.json`, which the web preview is tested against too:
 * both engines must place every part on exactly the same timeline spans
 * (loop phase reset per block, fade-out where a span cuts the loop). The
 * fixture is generated by `buildPlacementFixture()` below from this
 * implementation; regenerate it with
 * `REMIX_PARTS_PARITY_WRITE=1 npx jest src/tests/remix-parts-placement`.
 */

import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "fs";
import { tmpdir } from "os";
import { join } from "path";
import {
  deriveSectionGrid,
  type SectionGrid,
} from "../modules/remix/remix-arrangement";
import {
  structureTimeline,
  type RemixStructureBlock,
} from "../modules/remix/remix-structure";
import {
  isPitchedPartRole,
  partLengthSeconds,
  partPlacementSpans,
  partStretchPlan,
  PART_ROLES,
  PART_SPAN_FADE_SECONDS,
  readRenderedParts,
  REMIX_PARTS_DSP_VERSION,
  REMIX_PARTS_SCHEMA_VERSION,
  renderPartTrackInto,
  writePartTrackWav,
  type PartPlacementSpan,
} from "../modules/remix/remix-parts";
import {
  mixInputStretchStage,
  type StemMixFfmpegInput,
} from "../modules/remix/stem-audio-mixer";
import { deriveRemixAiDisclosure } from "../modules/catalog/ai-disclosure.policy";
import {
  groundingWithAiParts,
  renderIncludesAiParts,
} from "../modules/remix/remix-project.service";

const FIXTURE_PATH = join(
  __dirname,
  "../modules/remix/remix-parts-v1.parity.json",
);

type FixtureSegment = { section: number; outStartSec: number; outEndSec: number };
type FixtureCase = {
  name: string;
  grid: Pick<SectionGrid, "sections" | "sectionSeconds" | "bpm">;
  segments: FixtureSegment[];
  blocks: boolean[] | null;
  bars: number;
  loopSec: number;
  spans: PartPlacementSpan[];
};
type Fixture = {
  schemaVersion: string;
  dspVersion: string;
  note: string;
  fadeSeconds: number;
  cases: FixtureCase[];
};

function gridFor(bpm: number, firstBeatSec: number, durationSeconds: number): SectionGrid {
  const grid = deriveSectionGrid([
    {
      audioFeatures: {
        tempoBpm: bpm,
        tempoConfidence: 0.9,
        firstBeatSec,
        durationSeconds,
      },
    },
  ]);
  if (!grid) throw new Error("fixture grid did not derive");
  return grid;
}

/** The fixture, computed from this implementation (the "script"). */
function buildPlacementFixture(): Fixture {
  // 120 bpm, a 6 s pickup, 60 s: [0,6] [6,22] [22,38] [38,54] [54,60].
  const pickup120 = gridFor(120, 6, 60);
  // 93 bpm, anchored at 1.2 s: rounded 8-bar boundaries, a truncated tail.
  const odd93 = gridFor(93, 1.2, 70);
  // 100 bpm, anchor 0: no pickup, the first block is a full section.
  const flat100 = gridFor(100, 0, 70);
  const blocks = (sections: number[]): RemixStructureBlock[] =>
    sections.map((section) => ({ section }));
  const specs: Array<{
    name: string;
    grid: SectionGrid;
    structure: RemixStructureBlock[] | null;
    blocks: boolean[] | null;
    bars: number;
  }> = [
    { name: "plain timeline, 4 bars at 120", grid: pickup120, structure: null, blocks: null, bars: 4 },
    { name: "plain timeline, 8 bars at 120", grid: pickup120, structure: null, blocks: null, bars: 8 },
    {
      name: "reordered, repeated and removed blocks",
      grid: pickup120,
      structure: blocks([2, 1, 1, 3]),
      blocks: null,
      bars: 4,
    },
    {
      name: "blocks off",
      grid: pickup120,
      structure: null,
      blocks: [true, false, true, false, true],
      bars: 8,
    },
    {
      name: "a pickup block placed mid-song",
      grid: pickup120,
      structure: blocks([1, 0, 2, 0]),
      blocks: [true, true, false, true],
      bars: 4,
    },
    { name: "truncated tail, 4 bars at 93", grid: odd93, structure: null, blocks: null, bars: 4 },
    { name: "truncated tail, 8 bars at 93", grid: odd93, structure: null, blocks: null, bars: 8 },
    {
      name: "no pickup, 8 bars at 100, last block repeated",
      grid: flat100,
      structure: blocks([0, 1, 3, 3]),
      blocks: [true, true, true, true],
      bars: 8,
    },
  ];
  return {
    schemaVersion: REMIX_PARTS_SCHEMA_VERSION,
    dspVersion: REMIX_PARTS_DSP_VERSION,
    note: "Parity fixture for #1901: the render (backend partPlacementSpans) and the preview (web partPlacementSpans) must reproduce these spans exactly.",
    fadeSeconds: PART_SPAN_FADE_SECONDS,
    cases: specs.map((spec) => {
      const segments = structureTimeline(spec.grid, spec.structure).map(
        (segment) => ({
          section: segment.section,
          outStartSec: segment.outStartSec,
          outEndSec: segment.outEndSec,
        }),
      );
      const loopSec = partLengthSeconds(spec.grid.bpm!, spec.bars);
      const grid = {
        sections: spec.grid.sections,
        sectionSeconds: spec.grid.sectionSeconds,
        bpm: spec.grid.bpm,
      };
      return {
        name: spec.name,
        grid,
        segments,
        blocks: spec.blocks,
        bars: spec.bars,
        loopSec,
        spans: partPlacementSpans({ blocks: spec.blocks }, grid, segments, loopSec),
      };
    }),
  };
}

if (process.env.REMIX_PARTS_PARITY_WRITE === "1") {
  writeFileSync(FIXTURE_PATH, `${JSON.stringify(buildPlacementFixture(), null, 2)}\n`);
}

const fixture = JSON.parse(readFileSync(FIXTURE_PATH, "utf8")) as Fixture;

describe("remix-parts/v1 placement parity fixture (#1901)", () => {
  it("is exactly what the backend implementation generates", () => {
    expect(fixture).toEqual(buildPlacementFixture());
  });

  it("pins the versions and the fade length", () => {
    expect(fixture.schemaVersion).toBe(REMIX_PARTS_SCHEMA_VERSION);
    expect(fixture.dspVersion).toBe("remix-parts-dsp/v1");
    expect(fixture.fadeSeconds).toBe(0.01);
    expect(fixture.cases.length).toBeGreaterThanOrEqual(8);
  });

  it.each(fixture.cases.map((entry) => [entry.name, entry] as const))(
    "%s",
    (_name, entry) => {
      expect(
        partPlacementSpans({ blocks: entry.blocks }, entry.grid, entry.segments, entry.loopSec),
      ).toEqual(entry.spans);
    },
  );

  it("covers the placement rules", () => {
    const byName = new Map(fixture.cases.map((entry) => [entry.name, entry]));
    const plain = byName.get("plain timeline, 4 bars at 120")!;
    // Pickup skipped; full 16 s blocks are two whole 8 s loops; the 6 s
    // tail cuts the loop.
    expect(plain.spans).toEqual([
      { outStartSec: 6, outEndSec: 22, fadeOut: false },
      { outStartSec: 22, outEndSec: 38, fadeOut: false },
      { outStartSec: 38, outEndSec: 54, fadeOut: false },
      { outStartSec: 54, outEndSec: 60, fadeOut: true },
    ]);
    // A pickup block is skipped wherever it lands; block 2 is off.
    expect(byName.get("a pickup block placed mid-song")!.spans).toEqual([
      { outStartSec: 0, outEndSec: 16, fadeOut: false },
    ]);
    // Rounded boundaries (93 bpm) still count as whole loops within 1e-6;
    // the long first section (anchor < a quarter section) and the tail cut.
    const odd = byName.get("truncated tail, 4 bars at 93")!;
    expect(odd.spans.map((span) => span.fadeOut)).toEqual([true, false, false, true]);
    // An 8-bar loop longer than a 6 s block is cut: fade.
    expect(byName.get("plain timeline, 8 bars at 120")!.spans.at(-1)).toEqual({
      outStartSec: 54,
      outEndSec: 60,
      fadeOut: true,
    });
  });
});

describe("partPlacementSpans edge cases", () => {
  const grid = { sections: [{ startSec: 0, endSec: 8 }, { startSec: 8, endSec: 16 }], sectionSeconds: 8, bpm: 120 };
  const segments = [
    { section: 0, outStartSec: 0, outEndSec: 8 },
    { section: 1, outStartSec: 8, outEndSec: 16 },
  ];

  it("returns nothing for a non-positive or non-finite loop length", () => {
    expect(partPlacementSpans({}, grid, segments, 0)).toEqual([]);
    expect(partPlacementSpans({}, grid, segments, Number.NaN)).toEqual([]);
  });

  it("treats a missing or short blocks list as on", () => {
    expect(partPlacementSpans({ blocks: [false] }, grid, segments, 8)).toEqual([
      { outStartSec: 8, outEndSec: 16, fadeOut: false },
    ]);
  });
});

describe("renderPartTrackInto / writePartTrackWav (#1901)", () => {
  const SR = 1000;
  // A 10-frame stereo loop: L = 1..10, R = −(1..10).
  const loop = new Float32Array(20);
  for (let i = 0; i < 10; i += 1) {
    loop[i * 2] = i + 1;
    loop[i * 2 + 1] = -(i + 1);
  }
  const left = (out: Float32Array | Float64Array) =>
    Array.from({ length: out.length / 2 }, (_, f) => out[f * 2]);

  it("copies loop samples sample-exactly, resetting the phase per span", () => {
    const out = new Float64Array(2 * 40);
    renderPartTrackInto(
      out,
      0,
      40,
      loop,
      [
        { outStartSec: 0.005, outEndSec: 0.02, fadeOut: false },
        { outStartSec: 0.02, outEndSec: 0.034, fadeOut: false },
      ],
      SR,
    );
    expect(left(out)).toEqual([
      0, 0, 0, 0, 0,
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5,
      // Next span: the loop restarts at phase 0.
      1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4,
      0, 0, 0, 0, 0, 0,
    ]);
    expect(out[11]).toBe(-1);
  });

  it("fades the last 10 ms of a cut span linearly to its end", () => {
    const out = new Float64Array(2 * 30);
    renderPartTrackInto(out, 0, 30, loop, [{ outStartSec: 0, outEndSec: 0.025, fadeOut: true }], SR);
    // 10 ms at 1 kHz = 10 frames: gains 10/10 … 1/10 over frames 15..24.
    const expected = Array.from({ length: 25 }, (_, f) => {
      const sample = (f % 10) + 1;
      return f >= 15 ? (sample * (25 - f)) / 10 : sample;
    });
    left(out).slice(0, 25).forEach((value, f) => {
      expect(value).toBeCloseTo(expected[f], 12);
    });
    expect(left(out).slice(25)).toEqual([0, 0, 0, 0, 0]);
  });

  it("is chunk-invariant (any offset/window gives the same samples)", () => {
    const spans = [
      { outStartSec: 0.003, outEndSec: 0.027, fadeOut: true },
      { outStartSec: 0.031, outEndSec: 0.05, fadeOut: false },
    ];
    const whole = new Float32Array(2 * 60);
    renderPartTrackInto(whole, 0, 60, loop, spans, SR);
    const chunked = new Float32Array(2 * 60);
    for (let offset = 0; offset < 60; offset += 7) {
      const count = Math.min(7, 60 - offset);
      const window = new Float32Array(2 * count);
      renderPartTrackInto(window, offset, count, loop, spans, SR);
      chunked.set(window, offset * 2);
    }
    expect(Array.from(chunked)).toEqual(Array.from(whole));
  });

  it("streams a stereo 32-bit float WAV of ceil(duration·sr) frames", async () => {
    const dir = mkdtempSync(join(tmpdir(), "remix-part-track-"));
    try {
      const path = join(dir, "part.wav");
      const spans = [{ outStartSec: 0.5, outEndSec: 1.7, fadeOut: true }];
      // Longer than one 48 000-frame chunk at 48 kHz.
      const bigLoop = new Float32Array(2 * 4800);
      for (let f = 0; f < 4800; f += 1) {
        bigLoop[f * 2] = Math.sin(f / 10);
        bigLoop[f * 2 + 1] = Math.cos(f / 10);
      }
      const { frames } = await writePartTrackWav(path, bigLoop, spans, 2.0001);
      expect(frames).toBe(Math.ceil(2.0001 * 48000));
      const wav = readFileSync(path);
      expect(wav.toString("ascii", 0, 4)).toBe("RIFF");
      expect(wav.readUInt16LE(20)).toBe(3); // IEEE float
      expect(wav.readUInt16LE(22)).toBe(2); // stereo
      expect(wav.readUInt32LE(24)).toBe(48000);
      expect(wav.readUInt32LE(40)).toBe(frames * 2 * 4);
      const expected = new Float32Array(frames * 2);
      renderPartTrackInto(expected, 0, frames, bigLoop, spans, 48000);
      for (const frame of [0, 23_999, 24_000, 24_001, 48_000, 52_799, 52_800, 81_119, 81_599, 81_600, frames - 1]) {
        expect(wav.readFloatLE(44 + frame * 8)).toBe(expected[frame * 2]);
        expect(wav.readFloatLE(44 + frame * 8 + 4)).toBe(expected[frame * 2 + 1]);
      }
      // Loop phase: 1 s after the span start, phase = 48 000 mod 4 800 = 0.
      expect(wav.readFloatLE(44 + (24_000 + 48_000) * 8)).toBe(bigLoop[0]);
      // Silent before the span.
      expect(wav.readFloatLE(44 + 100 * 8)).toBe(0);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe("per-input stretch stage (#1901, #1898)", () => {
  const plan = { tempo: 0.9, semitones: 3 };
  const stem: StemMixFfmpegInput = { path: "/tmp/s", gainDb: 0, fxStemId: "s" };
  const layer: StemMixFfmpegInput = { path: "/tmp/l", gainDb: 0, aiLayer: true };
  const beat: StemMixFfmpegInput = { path: "/tmp/b", gainDb: 0, beat: true };
  const drums: StemMixFfmpegInput = { path: "/tmp/d", gainDb: 0, part: { role: "drums" } };
  const keys: StemMixFfmpegInput = { path: "/tmp/k", gainDb: 0, part: { role: "keys" } };

  it("stems, AI layers and pitched parts take the recipe plan", () => {
    expect(mixInputStretchStage(stem, plan)).toEqual(plan);
    expect(mixInputStretchStage(layer, plan)).toEqual(plan);
    expect(mixInputStretchStage(keys, plan)).toEqual(plan);
  });

  it("drum parts take the tempo only and are never transposed", () => {
    expect(mixInputStretchStage(drums, plan)).toEqual({ tempo: 0.9, semitones: 0 });
    // A key shift alone leaves drums untouched (identity stage skipped).
    expect(mixInputStretchStage(drums, { tempo: 1, semitones: 3 })).toBeNull();
    expect(mixInputStretchStage(keys, { tempo: 1, semitones: 3 })).toEqual({ tempo: 1, semitones: 3 });
  });

  it("the beat and a null plan never stretch", () => {
    expect(mixInputStretchStage(beat, plan)).toBeNull();
    expect(mixInputStretchStage(stem, null)).toBeNull();
    expect(partStretchPlan("bass", null)).toBeNull();
  });

  it.each([...PART_ROLES])("%s follows its pitched flag", (role) => {
    expect(partStretchPlan(role, plan)).toEqual({
      tempo: 0.9,
      semitones: isPitchedPartRole(role) ? 3 : 0,
    });
  });
});

describe("AI disclosure and grounding with parts (#1901)", () => {
  it("a stem mix with parts is AI-assisted (stem_plus_ai, instruments facet)", () => {
    expect(groundingWithAiParts("stem_audio", true)).toBe("stem_plus_ai");
    expect(groundingWithAiParts("stem_audio", false)).toBe("stem_audio");
    expect(groundingWithAiParts("audio_conditioned", true)).toBe("audio_conditioned");
    expect(deriveRemixAiDisclosure("stem_audio", { aiParts: true })).toEqual({
      level: "PARTLY",
      facets: ["instruments"],
    });
    expect(deriveRemixAiDisclosure("stem_plus_ai", { aiParts: true })).toEqual({
      level: "PARTLY",
      facets: ["production", "instruments"],
    });
    expect(deriveRemixAiDisclosure("prompt_only", { aiParts: true })).toEqual({
      level: "ALL",
      facets: ["instruments"],
    });
  });

  it("without parts the disclosure is unchanged", () => {
    expect(deriveRemixAiDisclosure("stem_audio")).toEqual({ level: "NONE", facets: [] });
    expect(deriveRemixAiDisclosure("stem_audio", { aiParts: false })).toEqual({
      level: "NONE",
      facets: [],
    });
    expect(deriveRemixAiDisclosure("stem_plus_ai")).toEqual({
      level: "PARTLY",
      facets: ["production"],
    });
  });

  it("reads rendered parts tolerantly from render metadata or conditioning", () => {
    const part = {
      partId: "p1",
      role: "keys",
      takeId: "t1",
      provider: "lyria",
      model: "lyria-002",
      promptVersion: "remix-part-prompt/v1",
      conformVersion: "remix-part-conform/v1",
      bars: 4,
      gainDb: -2,
    };
    expect(renderIncludesAiParts({ renderMetadata: { parts: [part] } })).toBe(true);
    expect(renderIncludesAiParts({ conditioningParts: { parts: [part] } })).toBe(true);
    expect(renderIncludesAiParts({ renderMetadata: { parts: [] } })).toBe(false);
    expect(renderIncludesAiParts({ renderMetadata: { parts: [{ partId: 1 }] } })).toBe(false);
    expect(renderIncludesAiParts({})).toBe(false);
    expect(readRenderedParts([part, "junk", { partId: "x" }])).toEqual([part]);
  });
});
