#!/usr/bin/env python3
"""Build a root-level copy of the Dataform project (#2115).

Managed GCP Dataform compiles a git repository whose ROOT holds
``workflow_settings.yaml``. This monorepo keeps the project in
``workers/analytics-dataflow/dataform/`` with only a ``workflow_settings.yaml.example``
template, so no deployment values are ever committed. This script produces a
self-contained tree that can be committed to a generated branch and pointed at
by a managed Dataform repository. Every placeholder value in the generated
settings file is overridden at deployment time through release-config
compilation overrides and vars.

Usage:
    python3 build_dataform_root_tree.py --source <dir> --out <dir> --source-commit <sha>

Standard library only.
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

SOURCE_PATH = "workers/analytics-dataflow/dataform"
BUILDER_PATH = "workers/analytics-dataflow/scripts/build_dataform_root_tree.py"
SETTINGS_EXAMPLE = "workflow_settings.yaml.example"
SETTINGS_NAME = "workflow_settings.yaml"
PROVENANCE_NAME = "GENERATED_FROM"

# Never copied from the source tree.
EXCLUDED_NAMES = frozenset({SETTINGS_EXAMPLE, SETTINGS_NAME, ".df-credentials.json", "node_modules"})
EXCLUDED_PREFIXES = (".df-",)

# Obviously non-deployment values. Deployments override all of them.
PLACEHOLDER_VALUES = {
    "YOUR_DATAFORM_EXECUTION_PROJECT": "resonate-placeholder-project",
    "YOUR_DATAFORM_OUTPUT_DATASET": "resonate_placeholder",
    "YOUR_BIGQUERY_LOCATION": "US",
    "YOUR_DATAFORM_ASSERTION_DATASET": "resonate_placeholder_assertions",
    "YOUR_ANALYTICS_PROJECT": "resonate-placeholder-project",
    "YOUR_ANALYTICS_DATASET": "resonate_placeholder",
}

_PLACEHOLDER = re.compile(r"YOUR_[A-Z0-9_]+")
_COMMIT = re.compile(r"^[0-9a-f]{7,64}$")

SETTINGS_HEADER = f"""\
# GENERATED FILE. Do not edit; do not commit deployment values here.
#
# Generated by {BUILDER_PATH}
# from {SOURCE_PATH}/{SETTINGS_EXAMPLE}.
# Every project, dataset and location below is an inert placeholder. Deployments
# override all values through Dataform release-config compilation overrides and
# vars. The source of truth is {SOURCE_PATH}.

"""


class BuildError(RuntimeError):
    """Raised when the root tree cannot be built safely."""


def _is_excluded(name: str) -> bool:
    return name in EXCLUDED_NAMES or name.startswith(EXCLUDED_PREFIXES)


def _copy_project_files(source_dir: Path, out_dir: Path) -> None:
    for path in sorted(source_dir.rglob("*")):
        relative = path.relative_to(source_dir)
        if any(_is_excluded(part) for part in relative.parts):
            continue
        target = out_dir / relative
        if path.is_dir():
            target.mkdir(parents=True, exist_ok=True)
        elif path.is_file():
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(path, target)


def _render_settings(example_text: str) -> str:
    lines = example_text.splitlines()
    # Drop the example's leading operator-instruction comment block.
    index = 0
    while index < len(lines) and (lines[index].startswith("#") or not lines[index].strip()):
        index += 1
    body = "\n".join(lines[index:]) + "\n"

    def substitute(match: re.Match[str]) -> str:
        key = match.group(0)
        if key not in PLACEHOLDER_VALUES:
            raise BuildError(f"no placeholder value defined for {key}")
        return PLACEHOLDER_VALUES[key]

    return SETTINGS_HEADER + _PLACEHOLDER.sub(substitute, body)


def _assert_no_placeholders(out_dir: Path) -> None:
    for path in sorted(out_dir.rglob("*")):
        if not path.is_file():
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        match = _PLACEHOLDER.search(text)
        if match:
            raise BuildError(
                f"unreplaced placeholder {match.group(0)} in {path.relative_to(out_dir)}"
            )


def build(source_dir: Path, out_dir: Path, source_commit: str) -> None:
    source_dir = Path(source_dir)
    out_dir = Path(out_dir)
    if not _COMMIT.fullmatch(source_commit):
        raise BuildError("source commit must be a lowercase hex git commit id")
    example = source_dir / SETTINGS_EXAMPLE
    if not example.is_file():
        raise BuildError(f"missing {SETTINGS_EXAMPLE} in {source_dir}")
    if not (source_dir / "definitions").is_dir():
        raise BuildError(f"missing definitions/ in {source_dir}")
    if out_dir.exists():
        if not out_dir.is_dir() or any(out_dir.iterdir()):
            raise BuildError(f"output directory must be empty: {out_dir}")
    else:
        out_dir.mkdir(parents=True)

    _copy_project_files(source_dir, out_dir)
    (out_dir / SETTINGS_NAME).write_text(
        _render_settings(example.read_text(encoding="utf-8")), encoding="utf-8"
    )
    (out_dir / PROVENANCE_NAME).write_text(
        "This tree is generated. Do not edit or merge it.\n"
        f"Generated by: {BUILDER_PATH}\n"
        f"Source path: {SOURCE_PATH}\n"
        f"Source commit: {source_commit}\n",
        encoding="utf-8",
    )
    _assert_no_placeholders(out_dir)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--source", required=True, type=Path, help="Dataform project directory")
    parser.add_argument("--out", required=True, type=Path, help="empty output directory")
    parser.add_argument("--source-commit", required=True, help="source git commit id")
    args = parser.parse_args(argv)
    try:
        build(args.source, args.out, args.source_commit)
    except BuildError as error:
        print(f"build_dataform_root_tree: {error}", file=sys.stderr)
        return 1
    print(f"Built Dataform root tree in {args.out} from {SOURCE_PATH}@{args.source_commit}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
