import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import AppShell from "../components/layout/AppShell";
import AuthProvider from "../components/auth/AuthProvider";
import PrivyProviderClient from "../components/auth/PrivyProviderClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const privyAppId = process.env.NEXT_PUBLIC_PRIVY_APP_ID;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${geistSans.variable} ${geistMono.variable}`}>
        {privyAppId ? (
          <PrivyProviderClient appId={privyAppId}>
            <AuthProvider>
              <AppShell>{children}</AppShell>
            </AuthProvider>
          </PrivyProviderClient>
        ) : (
          <AuthProvider>
            <AppShell>{children}</AppShell>
          </AuthProvider>
        )}
      </body>
    </html>
  );
}
